title:              "콘텐츠 육아일기"
tagline:            "뽀짝에서 반짝이 될 우리의 콘텐츠"
email:              "arimani100@naver.com"
description:        "닭띠 마케터가 병아리에서 장닭이 되는 성장과정 및 콘텐츠 제작기"
author:             "chaehyun"
baseurl:            ""
url:                "https://diarychae.me"
locale:             "ko_KR"
thumbnail:          "/img/chae_thumbnail.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: diarychae
